# Generated by Django 3.1.1 on 2021-03-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='s',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='part',
            name='s',
            field=models.FloatField(default=0),
        ),
    ]
