# Generated by Django 3.1.1 on 2021-03-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20210315_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
