# Generated by Django 3.1.1 on 2021-03-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_map_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='rank',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
